export const pkdSections = `["A – Rolnictwo, leśnictwo, łowiectwo i rybactwo",
							 "B – Górnictwo i wydobywanie",
							 "C – Przetwórstwo przemysłowe",
							 "D – Wytwarzanie i zaopatrywanie w energię elektryczną, gaz, parę wodną, gorącą wodę i powietrze do układów klimatyzacyjnych",
							 "E – Dostawa wody; gospodarowanie ściekami i odpadami oraz działalność związana z rekultywacją",
							 "F – Budownictwo",
							 "G – Handel hurtowy i detaliczny; naprawa pojazdów samochodowych, włączając motocykle",
							 "H – Transport i gospodarka magazynowa",
							 "I – Działalność związana z zakwaterowaniem i usługami gastronomicznymi",
							 "J – Informacja i komunikacja",
							 "K – Działalność finansowa i ubezpieczeniowa",
							 "L – Działalność związana z obsługą rynku nieruchomości",
							 "M – Działalność profesjonalna, naukowa i techniczna",
							 "N – Działalność w zakresie usług administrowania i działalność wspierająca",
							 "O – Administracja publiczna i obrona narodowa; obowiązkowe zabezpieczenia społeczne",
							 "P – Edukacja",
							 "Q – Opieka zdrowotna i pomoc społeczna",
							 "R – Działalność związana z kulturą, rozrywką i rekreacją",
							 "S – Pozostała działalność usługowa",
							 "T – Gospodarstwa domowe zatrudniające pracowników; gospodarstwa domowe produkujące wyroby i świadczące usługi na własne potrzeby",
							 "U – Organizacje i zespoły eksterytorialne"]`;

export const pkdDivisions = `["A01 - Uprawy rolne, chów i hodowla zwierząt, łowiectwo, włączając działalność usługową",
							  "A02 - Leśnictwo i pozyskiwanie drewna",
							  "A03 - RYBACTWO",
							  "B05 - Wydobywanie węgla kamiennego i węgla brunatnego (lignitu)",
							  "B06 - Górnictwo ropy naftowej i gazu ziemnego",
							  "B07 - Górnictwo rud metali",
							  "B08 - Pozostałe górnictwo i wydobywanie",
							  "B09 - Działalność usługowa wspomagająca górnictwo i wydobywanie",
							  "C10 - produkcja artykułów spożywczych",
							  "C11 - Produkcja napojów",
							  "C12 - Produkcja wyrobów tytoniowych",
							  "C13 - produkcja wyrobów tekstylnych",
							  "C14 - Produkcja odzieży",
							  "C15 - Produkcja skór i wyrobów ze skór wyprawionych",
							  "C16 - Produkcja wyrobów z drewna oraz korka, z wyłączeniem mebli; produkcja wyrobów ze słomy i materiałów używanych do wyplatania",
							  "C17 - Produkcja papieru i wyrobów z papieru",
							  "C18 - poligrafia i reprodukcja zapisanych nośników informacji",
							  "C19 - Wytwarzanie i przetwarzanie koksu i produktów rafinacji ropy naftowej",
							  "C20 - Produkcja chemikaliów i wyrobów chemicznych",
							  "C21 - Produkcja podstawowych substancji farmaceutycznych oraz leków i pozostałych wyrobów farmaceutycznych",
							  "C22 - Produkcja wyrobów z gumy i tworzyw sztucznych",
							  "C23 - Produkcja wyrobów z pozostałych mineralnych surowców niemetalicznych",
							  "C24 - Produkcja metali",
							  "C25 - Produkcja metalowych wyrobów gotowych, z wyłączeniem maszyn i urządzeń",
							  "C26 - Produkcja komputerów, wyrobów elektronicznych i optycznych",
							  "C27 - Produkcja urządzeń elektrycznych",
							  "C28 - Produkcja maszyn i urządzeń, gdzie indziej niesklasyfikowana",
							  "C29 - Produkcja pojazdów samochodowych, przyczep i naczep, z wyłączeniem motocykli",
							  "C30 - Produkcja pozostałego sprzętu transportowego",
							  "C31 - Produkcja mebli",
							  "C32 - Pozostała produkcja wyrobów",
							  "C33 - Naprawa, konserwacja i instalowanie maszyn i urządzeń",
							  "D35 - Wytwarzanie i zaopatrywanie w energię elektryczną, gaz, parę wodną, gorącą wodę i powietrze do układów klimatyzacyjnych",
							  "E36 - Pobór, uzdatnianie i dostarczanie wody",
							  "E37 - Odprowadzanie i oczyszczanie ścieków",
							  "E38 - Działalność związana ze zbieraniem, przetwarzaniem i unieszkodliwianiem odpadów; odzysk surowców",
							  "E39 - Działalność związana z rekultywacją i pozostała działalność usługowa związana z gospodarką odpadami",
							  "F41 - Roboty budowlane związane ze wznoszeniem budynków",
							  "F42 - Roboty związane z budową obiektów inżynierii lądowej i wodnej",
							  "F43 - Roboty budowlane specjalistyczne",
							  "G45 - Handel hurtowy i detaliczny pojazdami samochodowymi; naprawa pojazdów samochodowych",
							  "G46 - Handel hurtowy, z wyłączeniem handlu pojazdami samochodowymi",
							  "G47 - Handel detaliczny, z wyłączeniem handlu detalicznego pojazdami samochodowymi",
							  "H49 - transport lądowy oraz transport rurociągowy",
							  "H50 - transport wodny",
							  "H51 - transport lotniczy",
							  "H52 - Magazynowanie i działalność usługowa wspomagająca transport",
							  "H53 - działalność pocztowa i kurierska",
							  "I55 - Zakwaterowanie",
							  "I56 - Działalność usługowa związana z wyżywieniem",
							  "J58 - Działalność wydawnicza",
							  "J59 - Działalność związana z produkcją filmów, nagrań wideo, programów telewizyjnych, nagrań dźwiękowych i muzycznych",
							  "J60 - Nadawanie programów ogólnodostępnych i abonamentowych",
							  "J61 - telekomunikacja",
							  "J62 - Działalność związana z oprogramowaniem i doradztwem w zakresie informatyki oraz działalność powiązana",
							  "J63 - Działalność usługowa w zakresie informacji",
							  "K64 - Finansowa działalność usługowa, z wyłączeniem ubezpieczeń i funduszów emerytalnych",
							  "K65 - Ubezpieczenia, reasekuracja oraz fundusze emerytalne, z wyłączeniem obowiązkowego ubezpieczenia społecznego",
							  "K66 - Działalność wspomagająca usługi finansowe oraz ubezpieczenia i fundusze emerytalne",
							  "L68 - Działalność związana z obsługą rynku nieruchomości",
							  "M69 - Działalność prawnicza, rachunkowo-księgowa i doradztwo podatkowe",
							  "M70 - Działalność firm centralnych (head offices); doradztwo związane z zarządzaniem",
							  "M71 - Działalność w zakresie architektury i inżynierii; badania i analizy techniczne",
							  "M72 - Badania naukowe i prace rozwojowe",
							  "M73 - Reklama, badanie rynku i opinii publicznej",
							  "M74 - Pozostała działalność profesjonalna, naukowa i techniczna",
							  "M75 - Działalność weterynaryjna",
							  "N77 - Wynajem i dzierżawa",
							  "N78 - Działalność związana z zatrudnieniem",
							  "N79 - Działalność organizatorów turystyki, pośredników i agentów turystycznych oraz pozostała działalność usługowa w zakresie rezerwacji i działalności z nią związane",
							  "N80 - Działalność detektywistyczna i ochroniarska",
							  "N81 - Działalność usługowa związana z utrzymaniem porządku w budynkach i zagospodarowaniem terenów zieleni",
							  "N82 - Działalność związana z administracyjną obsługą biura i pozostała działalność wspomagająca prowadzenie działalności gospodarczej",
							  "O84 - administracja publiczna i obrona narodowa; obowiązkowe zabezpieczenia społeczne",
							  "P85 - edukacja",
							  "Q86 - Opieka zdrowotna",
							  "Q87 - Pomoc społeczna z zakwaterowaniem",
							  "Q88 - Pomoc społeczna bez zakwaterowania",
							  "R90 - Działalność twórcza związana z kulturą i rozrywką",
							  "R91 - Działalność bibliotek, archiwów, muzeów oraz pozostała działalność związana z kulturą",
							  "R92 - Działalność związana z grami losowymi i zakładami wzajemnymi",
							  "R93 - Działalność sportowa, rozrywkowa i rekreacyjna",
							  "S94 - Działalność organizacji członkowskich",
							  "S95 - Naprawa i konserwacja komputerów i artykułów użytku osobistego i domowego",
							  "S96 - Pozostała indywidualna działalność usługowa",
							  "T97 - Gospodarstwa domowe zatrudniające pracowników",
							  "T98 - Gospodarstwa domowe produkujące wyroby i świadczące usługi na własne potrzeby",
							  "U99 - Organizacje i zespoły eksterytorialne"]`;

export const pkdGroups = `["A011 - Uprawy rolne inne niż wieloletnie",
 "A012 - Uprawa roślin wieloletnich",
 "A013 - Rozmnażanie roślin",
 "A014 - Chów i hodowla zwierząt",
 "A015 - Uprawy rolne połączone z chowem i hodowlą zwierząt (działalność mieszana)",
 "A016 - Działalność usługowa wspomagająca rolnictwo i następująca po zbiorach",
 "A017 - Łowiectwo i pozyskiwanie zwierząt łownych, włączając działalność usługową",
 "A021 - Gospodarka leśna i pozostała działalność leśna, z wyłączeniem pozyskiwania produktów leśnych",
 "A022 - Pozyskiwanie drewna",
 "A023 - Pozyskiwanie dziko rosnących produktów leśnych, z wyłączeniem drewna",
 "A024 - Działalność usługowa związana z leśnictwem",
 "A031 - Rybołówstwo",
 "A032 - Chów i hodowla ryb oraz pozostałych organizmów wodnych",
 "B051 - Wydobywanie węgla kamiennego",
 "B052 - Wydobywanie węgla brunatnego (lignitu)",
 "B061 - Górnictwo ropy naftowej",
 "B062 - Górnictwo gazu ziemnego",
 "B071 - Górnictwo rud żelaza",
 "B072 - Górnictwo rud metali nieżelaznych",
 "B081 - Wydobywanie kamienia, piasku i gliny",
 "B089 - Górnictwo i wydobywanie, gdzie indziej niesklasyfikowane",
 "B091 - Działalność usługowa wspomagająca eksploatację złóż ropy naftowej i gazu ziemnego",
 "B099 - Działalność usługowa wspomagająca pozostałe górnictwo i wydobywanie",
 "C101 - Przetwarzanie i konserwowanie mięsa oraz produkcja wyrobów z mięsa",
 "C102 - Przetwarzanie i konserwowanie ryb, skorupiaków i mięczaków",
 "C103 - Przetwarzanie i konserwowanie owoców i warzyw",
 "C104 - Produkcja olejów i tłuszczów pochodzenia roślinnegoi zwierzęcego",
 "C105 - Wytwarzanie wyrobów mleczarskich",
 "C106 - Wytwarzanie produktów przemiału zbóż, skrobi i wyrobów skrobiowych",
 "C107 - Produkcja wyrobów piekarskich i mącznych",
 "C108 - Produkcja pozostałych artykułów spożywczych",
 "C109 - Produkcja gotowych paszy i karmy dla zwierząt",
 "C110 - Produkcja napojów",
 "C120 - Produkcja wyrobów tytoniowych",
 "C133 - Wykończanie wyrobów włókienniczych",
 "C139 - Produkcja pozostałych wyrobów tekstylnych",
 "C141 - Produkcja odzieży, z wyłączeniem wyrobów futrzarskich",
 "C142 - Produkcja wyrobów futrzarskich",
 "C143 - Produkcja odzieży dzianej",
 "C151 - Wyprawa skór, garbowanie; wyprawa i barwienie skór futerkowych; produkcja toreb bagażowych, toreb ręcznych i podobnych wyrobów kaletniczych; produkcja wyrobów rymarskich",
 "C152 - Produkcja obuwia",
 "C161 - Produkcja wyrobów tartacznych",
 "C162 - Produkcja wyrobów z drewna, korka, słomy i materiałów używanych do wyplatania",
 "C171 - Produkcja masy włóknistej, papieru i tektury",
 "C172 - Produkcja wyrobów z papieru i tektury",
 "C181 - Drukowanie i działalność usługowa związana z poligrafią",
 "C182 - Reprodukcja zapisanych nośników informacji",
 "C191 - Wytwarzanie i przetwarzanie koksu",
 "C192 - Wytwarzanie i przetwarzanie produktów rafinacji ropy naftowej",
 "C201 - Produkcja podstawowych chemikaliów, nawozów i związków azotowych, tworzyw sztucznych i kauczuku syntetycznego w formach podstawowych",
 "C202 - Produkcja pestycydów i pozostałych środków agrochemicznych",
 "C203 - Produkcja farb, lakierów i podobnych powłok, farb drukarskich i mas uszczelniających",
 "C204 - Produkcja mydła i detergentów, środków myjących i czyszczących, wyrobów kosmetycznych i toaletowych",
 "C205 - Produkcja pozostałych wyrobów chemicznych",
 "C206 - Produkcja włókien chemicznych",
 "C211 - Produkcja podstawowych substancji farmaceutycznych",
 "C212 - Produkcja leków i pozostałych wyrobów farmaceutycznych",
 "C221 - Produkcja wyrobów z gumy",
 "C222 - Produkcja wyrobów z tworzyw sztucznych",
 "C231 - Produkcja szkła i wyrobów ze szkła",
 "C232 - Produkcja wyrobów ogniotrwałych",
 "C233 - Produkcja ceramicznych materiałów budowlanych",
 "C234 - Produkcja pozostałych wyrobów z porcelany i ceramiki",
 "C235 - Produkcja cementu, wapna i gipsu",
 "C236 - Produkcja wyrobów z betonu, cementu i gipsu",
 "C237 - Cięcie, formowanie i wykańczanie kamienia",
 "C239 - Produkcja wyrobów ściernych i pozostałych wyrobów z mineralnych surowców niemetalicznych, gdzie indziej niesklasyfikowana",
 "C241 - Produkcja surówki, żelazostopów, żeliwa i stali oraz wyrobów hutniczych",
 "C242 - Produkcja rur, przewodów, kształtowników zamkniętych i łączników, ze stali",
 "C243 - Produkcja pozostałych wyrobów ze stali poddanej wstępnej obróbce",
 "C244 - Produkcja metali szlachetnych i innych metali nieżelaznych",
 "C245 - Odlewnictwo metali",
 "C251 - Produkcja metalowych elementów konstrukcyjnych",
 "C252 - Produkcja zbiorników, cystern i pojemników metalowych",
 "C253 - Produkcja wytwornic pary, z wyłączeniem kotłów do centralnego ogrzewania gorącą wodą",
 "C254 - Produkcja broni i amunicji",
 "C255 - Kucie, prasowanie, wytłaczanie i walcowanie metali; metalurgia proszków",
 "C256 - Obróbka metali i nakładanie powłok na metale; obróbka mechaniczna elementów metalowych",
 "C257 - Produkcja wyrobów nożowniczych, sztućców, narzędzi i wyrobów metalowych ogólnego przeznaczenia",
 "C259 - Produkcja pozostałych gotowych wyrobów metalowych",
 "C261 - Produkcja elektronicznych elementów i obwodów drukowanych",
 "C262 - Produkcja komputerów i urządzeń peryferyjnych",
 "C263 - Produkcja sprzętu (tele)komunikacyjnego",
 "C264 - Produkcja elektronicznego sprzętu powszechnego użytku",
 "C265 - Produkcja instrumentów i przyrządów pomiarowych, kontrolnych i nawigacyjnych; produkcja zegarków i zegarów",
 "C266 - Produkcja urządzeń napromieniowujących, sprzętu elektromedycznego i elektroterapeutycznego",
 "C267 - Produkcja instrumentów optycznych i sprzętu fotograficznego",
 "C268 - Produkcja magnetycznych i optycznych niezapisanych nośników informacji",
 "C271 - Produkcja elektrycznych silników, prądnic, transformatorów, aparatury rozdzielczej i sterowniczej energii elektrycznej",
 "C272 - Produkcja baterii i akumulatorów",
 "C273 - Produkcja izolowanych przewodów i kabli oraz sprzętu instalacyjnego",
 "C274 - Produkcja elektrycznego sprzętu oświetleniowego",
 "C275 - Produkcja sprzętu gospodarstwa domowego",
 "C279 - Produkcja pozostałego sprzętu elektrycznego",
 "C281 - Produkcja maszyn ogólnego przeznaczenia",
 "C282 - Produkcja pozostałych maszyn ogólnego przeznaczenia",
 "C283 - Produkcja maszyn dla rolnictwa i leśnictwa",
 "C284 - Produkcja maszyn i narzędzi mechanicznych",
 "C289 - Produkcja pozostałych maszyn specjalnego przeznaczenia",
 "C292 - Produkcja nadwozi do pojazdów silnikowych; produkcja przyczep i naczep",
 "C293 - Produkcja części i akcesoriów do pojazdów silnikowych",
 "C301 - Produkcja statków i łodzi",
 "C302 - Produkcja lokomotyw kolejowych oraz taboru szynowego",
 "C303 - Produkcja statków powietrznych, statków kosmicznych i podobnych maszyn",
 "C304 - Produkcja wojskowych pojazdów bojowych",
 "C309 - Produkcja sprzętu transportowego, gdzie indziej niesklasyfikowana",
 "C310 - Produkcja mebli",
 "C321 - Produkcja wyrobów jubilerskich, biżuterii i podobnych wyrobów",
 "C322 - Produkcja instrumentów muzycznych",
 "C323 - Produkcja sprzętu sportowego",
 "C324 - Produkcja gier i zabawek",
 "C325 - Produkcja urządzeń, instrumentów oraz wyrobów medycznych, włączając dentystyczne",
 "C329 - Produkcja wyrobów, gdzie indziej niesklasyfikowana",
 "C331 - Naprawa i konserwacja metalowych wyrobów gotowych, maszyn i urządzeń",
 "C332 - Instalowanie maszyn przemysłowych, sprzętu i wyposażenia",
 "D351 - Wytwarzanie, przesyłanie, dystrybucja i handel energią elektryczną",
 "D352 - Wytwarzanie paliw gazowych; dystrybucja i handel paliwami gazowymi w systemie sieciowym",
 "D353 - Wytwarzanie i zaopatrywanie w parę wodną, gorącą wodę i powietrze do układów klimatyzacyjnych",
 "E360 - Pobór, uzdatnianie i dostarczanie wody",
 "E370 - Odprowadzanie i oczyszczanie ścieków",
 "E381 - Zbieranie odpadów",
 "E382 - Przetwarzanie i unieszkodliwianie odpadów",
 "E383 - Odzysk surowców",
 "E390 - Działalność związana z rekultywacją i pozostała działalność usługowa związana z gospodarką odpadami",
 "F411 - Realizacja projektów budowlanych związanych ze wznoszeniem budynków",
 "F412 - Roboty budowlane związane ze wznoszeniem budynków mieszkalnych i niemieszkalnych",
 "F421 - Roboty związane z budową dróg kołowych i szynowych",
 "F422 - Roboty związane z budową rurociągów, linii telekomunikacyjnych i elektroenergetycznych",
 "F431 - Rozbiórka i przygotowanie terenu pod budowę",
 "F432 - Wykonywanie instalacji elektrycznych, wodno-kanalizacyjnych i pozostałych instalacji budowlanych",
 "F433 - Wykonywanie robót budowlanych wykończeniowych",
 "F439 - Pozostałe specjalistyczne roboty budowlane",
 "G451 - Sprzedaż hurtowa i detaliczna pojazdów samochodowych, z wyłączeniem motocykli",
 "G452 - Konserwacja i naprawa pojazdów samochodowych, z wyłączeniem motocykli",
 "G453 - Sprzedaż hurtowa i detaliczna części i akcesoriów do pojazdów samochodowych, z wyłączeniem motocykli",
 "G454 - Sprzedaż hurtowa i detaliczna motocykli, ich naprawa i konserwacja oraz sprzedaż hurtowa i detaliczna części i akcesoriów do nich",
 "G461 - Sprzedaż hurtowa realizowana na zlecenie",
 "G462 - Sprzedaż hurtowa płodów rolnych i żywych zwierząt",
 "G463 - Sprzedaż hurtowa żywności, napojów i wyrobów tytoniowych",
 "G464 - Sprzedaż hurtowa artykułów użytku domowego",
 "G465 - Sprzedaż hurtowa narzędzi technologii informacyjnej i komunikacyjnej",
 "G466 - Sprzedaż hurtowa maszyn, urządzeń i dodatkowego wyposażenia",
 "G467 - Pozostała wyspecjalizowana sprzedaż hurtowa",
 "G469 - Sprzedaż hurtowa niewyspecjalizowana",
 "G471 - Sprzedaż detaliczna prowadzona w niewyspecjalizowanych sklepach",
 "G472 - Sprzedaż detaliczna żywności, napojów i wyrobów tytoniowych prowadzona w wyspecjalizowanych sklepach",
 "G473 - Sprzedaż detaliczna paliw do pojazdów silnikowych na stacjach paliw",
 "G474 - Sprzedaż detaliczna narzędzi technologii informacyjnej i komunikacyjnej prowadzona w wyspecjalizowanych sklepach",
 "G475 - Sprzedaż detaliczna artykułów użytku domowego prowadzona w wyspecjalizowanych sklepach",
 "G476 - Sprzedaż detaliczna wyrobów związanych z kulturą i rekreacją prowadzona w wyspecjalizowanych sklepach",
 "G477 - Sprzedaż detaliczna pozostałych wyrobów prowadzona w wyspecjalizowanych sklepach",
 "G478 - Sprzedaż detaliczna prowadzona na straganach i targowiskach",
 "G479 - Sprzedaż detaliczna prowadzona poza siecią sklepową, straganami i targowiskami",
 "H491 - Transport kolejowy pasażerski międzymiastowy",
 "H492 - Transport kolejowy towarów",
 "H493 - Pozostały transport lądowy pasażerski",
 "H494 - Transport drogowy towarów oraz działalność usługowa związana z przeprowadzkami",
 "H501 - Transport morski i przybrzeżny pasażerski",
 "H502 - Transport morski i przybrzeżny towarów",
 "H503 - Transport wodny śródlądowy pasażerski",
 "H504 - Transport wodny śródlądowy towarów",
 "H511 - Transport lotniczy pasażerski",
 "H512 - Transport lotniczy towarów i transport kosmiczny",
 "H522 - Działalność usługowa wspomagająca transport",
 "H531 - Działalność pocztowa objęta obowiązkiem świadczenia usług powszechnych (operatora publicznego)",
 "H532 - Pozostała działalność pocztowa i kurierska",
 "I551 - Hotele i podobne obiekty zakwaterowania",
 "I552 - Obiekty noclegowe turystyczne i miejsca krótkotrwałego zakwaterowania",
 "I553 - Pola kempingowe (włączając pola dla pojazdów kempingowych) i pola namiotowe",
 "I559 - Pozostałe zakwaterowanie",
 "I562 - Przygotowywanie żywności dla odbiorców zewnętrznych (katering) i pozostała gastronomiczna działalność usługowa",
 "I563 - Przygotowywanie i podawanie napojów",
 "J581 - Wydawanie książek i periodyków oraz pozostała działalność wydawnicza, z wyłączeniem w zakresie oprogramowania",
 "J582 - Działalność wydawnicza w zakresie oprogramowania",
 "J591 - Działalność związana z filmami, nagraniami wideo i programami telewizyjnymi",
 "J592 - Działalność w zakresie nagrań dźwiękowych i muzycznych",
 "J601 - Nadawanie programów radiofonicznych",
 "J602 - Nadawanie programów telewizyjnych ogólnodostępnych i abonamentowych",
 "J611 - Działalność w zakresie telekomunikacji przewodowej",
 "J612 - Działalność w zakresie telekomunikacji bezprzewodowej, z wyłączeniem telekomunikacji satelitarnej",
 "J613 - Działalność w zakresie telekomunikacji satelitarnej",
 "J619 - Działalność w zakresie pozostałej telekomunikacji",
 "J620 - Działalność związana z oprogramowaniem i doradztwem w zakresie informatyki oraz działalność powiązana",
 "J631 - Przetwarzanie danych; zarządzanie stronami internetowymi (hosting) i podobna działalność; działalność portali internetowych",
 "K641 - Pośrednictwo pieniężne",
 "K642 - Działalność holdingów finansowych",
 "K643 - Działalność trustów, funduszów i podobnych instytucji finansowych",
 "K649 - Pozostała finansowa działalność usługowa, z wyłączeniem ubezpieczeń i funduszów emerytalnych",
 "K651 - Ubezpieczenia",
 "K652 - Reasekuracja",
 "K653 - Fundusze emerytalne",
 "K661 - Działalność wspomagająca usługi finansowe, z wyłączeniem ubezpieczeń i funduszów emerytalnych",
 "K662 - Działalność wspomagająca ubezpieczenia i fundusze emerytalne",
 "K663 - Działalność związana z zarządzaniem funduszami",
 "L681 - Kupno i sprzedaż nieruchomości na własny rachunek",
 "L682 - Wynajem i zarządzanie nieruchomościami własnymi lub dzierżawionymi",
 "L683 - Działalność związana z obsługą rynku nieruchomości wykonywana na zlecenie",
 "M691 - Działalność prawnicza",
 "M692 - Działalność rachunkowo-księgowa; doradztwo podatkowe",
 "M701 - Działalność firm centralnych (head offices) i holdingów, z wyłączeniem holdingów finansowych",
 "M702 - Doradztwo związane z zarządzaniem",
 "M711 - Działalność w zakresie architektury i inżynierii oraz związane z nią doradztwo techniczne",
 "M721 - Badania naukowe i prace rozwojowe w dziedzinie nauk przyrodniczych i technicznych",
 "M722 - Badania naukowe i prace rozwojowe w dziedzinie nauk społecznych i humanistycznych",
 "M731 - Reklama",
 "M732 - Badanie rynku i opinii publicznej",
 "M741 - Działalność w zakresie specjalistycznego projektowania",
 "M742 - Działalność fotograficzna",
 "M743 - Działalność związana z tłumaczeniami",
 "M749 - Pozostała działalność profesjonalna, naukowa i techniczna, gdzie indziej niesklasyfikowana",
 "M750 - Działalność weterynaryjna",
 "N771 - Wynajem i dzierżawa pojazdów samochodowych, z wyłączeniem motocykli",
 "N772 - Wypożyczanie i dzierżawa artykułów użytku osobistego i domowego",
 "N773 - Wynajem i dzierżawa pozostałych maszyn, urządzeń oraz dóbr materialnych",
 "N774 - Dzierżawa własności intelektualnej i podobnych produktów, z wyłączeniem prac chronionych prawem autorskim",
 "N781 - Działalność związana z wyszukiwaniem miejsc pracy i pozyskiwaniem pracowników",
 "N782 - Działalność agencji pracy tymczasowej",
 "N783 - Pozostała działalność związana z udostępnianiem pracowników",
 "N791 - Działalność agentów i pośredników turystycznych oraz organizatorów turystyki",
 "N801 - Działalność ochroniarska, z wyłączeniem obsługi systemów bezpieczeństwa",
 "N802 - Działalność ochroniarska w zakresie obsługi systemów bezpieczeństwa",
 "N803 - Działalność detektywistyczna",
 "N811 - Działalność pomocnicza związana z utrzymaniem porządku w budynkach",
 "N812 - Sprzątanie obiektów",
 "N813 - Działalność usługowa związana z zagospodarowaniem terenów zieleni",
 "N821 - Działalność związana z administracyjną obsługą biura, włączając działalność wspomagającą",
 "N822 - Działalność centrów telefonicznych (call center)",
 "N823 - Działalność związana z organizacją targów, wystaw i kongresów",
 "N829 - Działalność komercyjna, gdzie indziej niesklasyfikowana",
 "O841 - Administracja publiczna oraz polityka gospodarcza i społeczna",
 "O842 - Usługi na rzecz całego społeczeństwa",
 "O843 - Obowiązkowe zabezpieczenia społeczne",
 "P851 - Wychowanie przedszkolne",
 "P852 - Szkoły podstawowe",
 "P854 - Szkoły policealne oraz wyższe",
 "P855 - Pozaszkolne formy edukacji",
 "P856 - Działalność wspomagająca edukację",
 "Q861 - Działalność szpitali",
 "Q862 - Praktyka lekarska",
 "Q871 - Pomoc społeczna z zakwaterowaniem zapewniająca opiekę pielęgniarską",
 "Q872 - Pomoc społeczna z zakwaterowaniem dla osób z zaburzeniami psychicznymi",
 "Q873 - Pomoc społeczna z zakwaterowaniem dla osób w podeszłym wieku i osób niepełnosprawnych",
 "Q879 - Pozostała pomoc społeczna z zakwaterowaniem",
 "Q881 - Pomoc społeczna bez zakwaterowania dla osób w podeszłym wieku i osób niepełnosprawnych",
 "Q889 - Pozostała pomoc społeczna bez zakwaterowania",
 "R900 - Działalność twórcza związana z kulturą i rozrywką",
 "R910 - Działalność bibliotek, archiwów, muzeów oraz pozostała działalność związana z kulturą",
 "R920 - Działalność związana z grami losowymi i zakładami wzajemnymi",
 "R931 - Działalność związana ze sportem",
 "R932 - Działalność rozrywkowa i rekreacyjna",
 "S941 - Działalność organizacji komercyjnych, pracodawców oraz organizacji profesjonalnych",
 "S942 - Działalność związków zawodowych",
 "S949 - Działalność pozostałych organizacji członkowskich",
 "S951 - Naprawa i konserwacja komputerów i sprzętu komunikacyjnego",
 "S952 - Naprawa i konserwacja artykułów użytku osobistego i domowego",
 "S960 - Pozostała indywidualna działalność usługowa",
 "T970 - Gospodarstwa domowe zatrudniające pracowników",
 "T981 - Gospodarstwa domowe produkujące wyroby na własne potrzeby",
 "T982 - Gospodarstwa domowe świadczące usługi na własne potrzeby",
 "U990 - Organizacje i zespoły eksterytorialne"]`;

export const pkdClasses = `["A0111 - Uprawa zbóż, roślin strączkowych i roślin oleistych na nasiona, z wyłączeniem ryżu",
							"A0112 - Uprawa ryżu",
							"A0113 - Uprawa warzyw, włączając melony oraz uprawa roślin korzeniowych i roślin bulwiastych",
							"A0114 - Uprawa trzciny cukrowej",
							"A0115 - Uprawa tytoniu",
							"A0116 - Uprawa roślin włóknistych",
							"A0119 - Pozostałe uprawy rolne inne niż wieloletnie",
							"A0121 - Uprawa winogron",
							"A0122 - Uprawa drzew i krzewów owocowych tropikalnych i podzwrotnikowych",
							"A0123 - Uprawa drzew i krzewów owocowych cytrusowych",
							"A0124 - Uprawa drzew i krzewów owocowych ziarnkowych i pestkowych",
							"A0125 - Uprawa pozostałych drzew i krzewów owocowych oraz orzechów",
							"A0126 - Uprawa drzew oleistych",
							"A0127 - Uprawa roślin wykorzystywanych do produkcji napojów",
							"A0128 - Uprawa roślin przyprawowych i aromatycznych oraz roślin wykorzystywanych do produkcji leków i wyrobów farmaceutycznych",
							"A0129 - Uprawa pozostałych roślin wieloletnich",
							"A0130 - Rozmnażanie roślin",
							"A0141 - Chów i hodowla bydła mlecznego",
							"A0142 - Chów i hodowla pozostałego bydła i bawołów",
							"A0143 - Chów i hodowla koni i pozostałych zwierząt koniowatych",
							"A0144 - Chów i hodowla wielbłądów i zwierząt wielbłądowatych",
							"A0145 - Chów i hodowla owiec i kóz",
							"A0146 - Chów i hodowla świń",
							"A0147 - Chów i hodowla drobiu",
							"A0149 - Chów i hodowla pozostałych zwierząt",
							"A0150 - Uprawy rolne połączone z chowem i hodowlą zwierząt (działalność mieszana)",
							"A0161 - Działalność usługowa wspomagająca produkcję roślinną",
							"A0162 - Działalność usługowa wspomagająca chów i hodowlę zwierząt gospodarskich",
							"A0163 - Działalność usługowa następująca po zbiorach",
							"A0164 - Obróbka nasion dla celów rozmnażania roślin",
							"A0170 - Łowiectwo i pozyskiwanie zwierząt łownych, włączając działalność usługową",
							"A0210 - Gospodarka leśna i pozostała działalność leśna, z wyłączeniem pozyskiwania produktów leśnych",
							"A0220 - Pozyskiwanie drewna",
							"A0230 - Pozyskiwanie dziko rosnących produktów leśnych, z wyłączeniem drewna",
							"A0240 - Działalność usługowa związana z leśnictwem",
							"A0311 - Rybołówstwo w wodach morskich",
							"A0312 - Rybołówstwo w wodach śródlądowych",
							"A0321 - Chów i hodowla ryb oraz pozostałych organizmów wodnych w wodach morskich",
							"A0322 - Chów i hodowla ryb oraz pozostałych organizmów wodnych w wodach śródlądowych",
							"B0510 - Wydobywanie węgla kamiennego",
							"B0520 - Wydobywanie węgla brunatnego (lignitu)",
							"B0610 - Górnictwo ropy naftowej",
							"B0620 - Górnictwo gazu ziemnego",
							"B0710 - Górnictwo rud żelaza",
							"B0721 - Górnictwo rud uranu i toru",
							"B0729 - Górnictwo pozostałych rud metali nieżelaznych",
							"B0811 - Wydobywanie kamieni ozdobnych oraz kamienia dla potrzeb budownictwa, skał wapiennych, gipsu, kredy i łupków",
							"B0812 - Wydobywanie żwiru i piasku; wydobywanie gliny i kaolinu",
							"B0891 - Wydobywanie minerałów dla przemysłu chemicznego oraz do produkcji nawozów",
							"B0892 - Wydobywanie torfu",
							"B0893 - Wydobywanie soli",
							"B0899 - Pozostałe górnictwo i wydobywanie, gdzie indziej niesklasyfikowane",
							"B0910 - Działalność usługowa wspomagająca eksploatację złóż ropy naftowej i gazu ziemnego",
							"B0990 - Działalność usługowa wspomagająca pozostałe górnictwo i wydobywanie",
							"C1011 - Przetwarzanie i konserwowanie mięsa, z wyłączeniem mięsa z drobiu",
							"C1012 - Przetwarzanie i konserwowanie mięsa z drobiu",
							"C1013 - Produkcja wyrobów z mięsa, włączając wyroby z mięsa drobiowego",
							"C1020 - Przetwarzanie i konserwowanie ryb, skorupiaków i mięczaków",
							"C1031 - Przetwarzanie i konserwowanie ziemniaków",
							"C1032 - Produkcja soków z owoców i warzyw",
							"C1039 - Pozostałe przetwarzanie i konserwowanie owoców i warzyw",
							"C1041 - Produkcja olejów i pozostałych tłuszczów płynnych",
							"C1042 - Produkcja margaryny i podobnych tłuszczów jadalnych",
							"C1051 - Przetwórstwo mleka i wyrób serów",
							"C1052 - Produkcja lodów",
							"C1061 - Wytwarzanie produktów przemiału zbóż",
							"C1062 - Wytwarzanie skrobi i wyrobów skrobiowych",
							"C1071 - Produkcja pieczywa; produkcja świeżych wyrobów ciastkarskich i ciastek",
							"C1072 - Produkcja sucharów i herbatników; produkcja konserwowanych wyrobów ciastkarskich i ciastek",
							"C1073 - Produkcja makaronów, klusek, kuskusu i podobnych wyrobów mącznych",
							"C1081 - Produkcja cukru",
							"C1082 - Produkcja kakao, czekolady i wyrobów cukierniczych",
							"C1083 - Przetwórstwo herbaty i kawy",
							"C1084 - Produkcja przypraw",
							"C1085 - Wytwarzanie gotowych posiłków i dań",
							"C1086 - Produkcja artykułów spożywczych homogenizowanych i żywności dietetycznej",
							"C1089 - Produkcja pozostałych artykułów spożywczych, gdzie indziej niesklasyfikowana",
							"C1091 - Produkcja gotowej paszy dla zwierząt gospodarskich",
							"C1092 - Produkcja gotowej karmy dla zwierząt domowych",
							"C1101 - Destylowanie, rektyfikowanie i mieszanie alkoholi",
							"C1102 - Produkcja win gronowych",
							"C1103 - Produkcja cydru i pozostałych win owocowych",
							"C1104 - Produkcja pozostałych niedestylowanych napojów fermentowanych",
							"C1105 - Produkcja piwa",
							"C1106 - Produkcja słodu",
							"C1107 - Produkcja napojów bezalkoholowych; produkcja wód mineralnych i pozostałych wód butelkowanych",
							"C1200 - PRODUKCJA WYROBÓW TYTONIOWYCH",
							"C1310 - Produkcja przędzy",
							"C1320 - Produkcja tkanin",
							"C1330 - Wykończanie wyrobów włókienniczych",
							"C1391 - Produkcja dzianin metrażowych",
							"C1392 - Produkcja gotowych wyrobów tekstylnych",
							"C1393 - Produkcja dywanów i chodników",
							"C1394 - Produkcja wyrobów powroźniczych, lin, szpagatów i wyrobów sieciowych",
							"C1395 - Produkcja włóknin i wyrobów wykonanych z włóknin, z wyłączeniem odzieży",
							"C1396 - Produkcja pozostałych technicznych i przemysłowych wyrobów tekstylnych",
							"C1399 - Produkcja pozostałych wyrobów tekstylnych, gdzie indziej niesklasyfikowana",
							"C1411 - Produkcja odzieży skórzanej",
							"C1412 - Produkcja odzieży roboczej",
							"C1413 - Produkcja pozostałej odzieży wierzchniej",
							"C1414 - Produkcja bielizny",
							"C1419 - Produkcja pozostałej odzieży i dodatków do odzieży",
							"C1420 - Produkcja wyrobów futrzarskich",
							"C1431 - Produkcja wyrobów pończoszniczych",
							"C1439 - Produkcja pozostałej odzieży dzianej",
							"C1511 - Wyprawa skór, garbowanie; wyprawa i barwienie skór futerkowych",
							"C1512 - Produkcja toreb bagażowych, toreb ręcznych i podobnych wyrobów kaletniczych; produkcja wyrobów rymarskich",
							"C1520 - Produkcja obuwia",
							"C1610 - Produkcja wyrobów tartacznych",
							"C1621 - Produkcja arkuszy fornirowych i płyt wykonanych na bazie drewna",
							"C1622 - Produkcja gotowych parkietów podłogowych",
							"C1623 - Produkcja pozostałych wyrobów stolarskich i ciesielskich dla budownictwa",
							"C1624 - Produkcja opakowań drewnianych",
							"C1629 - Produkcja pozostałych wyrobów z drewna; produkcja wyrobów z korka, słomy i materiałów używanych do wyplatania",
							"C1711 - Produkcja masy włóknistej",
							"C1712 - Produkcja papieru i tektury",
							"C1721 - Produkcja papieru falistego i tektury falistej oraz opakowań z papieru i tektury",
							"C1722 - Produkcja artykułów gospodarstwa domowego, toaletowych i sanitarnych",
							"C1723 - Produkcja artykułów piśmiennych",
							"C1724 - Produkcja tapet",
							"C1729 - Produkcja pozostałych wyrobów z papieru i tektury",
							"C1811 - Drukowanie gazet",
							"C1812 - Pozostałe drukowanie",
							"C1813 - Działalność usługowa związana z przygotowywaniem do druku",
							"C1814 - Introligatorstwo i podobne usługi",
							"C1820 - Reprodukcja zapisanych nośników informacji",
							"C1910 - Wytwarzanie i przetwarzanie koksu",
							"C1920 - Wytwarzanie i przetwarzanie produktów rafinacji ropy naftowej",
							"C2011 - Produkcja gazów technicznych",
							"C2012 - Produkcja barwników i pigmentów",
							"C2013 - Produkcja pozostałych podstawowych chemikaliów nieorganicznych",
							"C2014 - Produkcja pozostałych podstawowych chemikaliów organicznych",
							"C2015 - Produkcja nawozów i związków azotowych",
							"C2016 - Produkcja tworzyw sztucznych w formach podstawowych",
							"C2017 - Produkcja kauczuku syntetycznego w formach podstawowych",
							"C2020 - Produkcja pestycydów i pozostałych środków agrochemicznych",
							"C2030 - Produkcja farb, lakierów i podobnych powłok, farb drukarskich i mas uszczelniających",
							"C2041 - Produkcja mydła i detergentów, środków myjących i czyszczących",
							"C2042 - Produkcja wyrobów kosmetycznych i toaletowych",
							"C2051 - Produkcja materiałów wybuchowych",
							"C2052 - Produkcja klejów",
							"C2053 - Produkcja olejków eterycznych",
							"C2059 - Produkcja pozostałych wyrobów chemicznych, gdzie indziej niesklasyfikowana",
							"C2060 - Produkcja włókien chemicznych",
							"C2110 - Produkcja podstawowych substancji farmaceutycznych",
							"C2120 - Produkcja leków i pozostałych wyrobów farmaceutycznych",
							"C2211 - Produkcja opon i dętek z gumy; bieżnikowanie i regenerowanie opon z gumy",
							"C2219 - Produkcja pozostałych wyrobów z gumy",
							"C2221 - Produkcja płyt, arkuszy, rur i kształtowników z tworzyw sztucznych",
							"C2222 - Produkcja opakowań z tworzyw sztucznych",
							"C2223 - Produkcja wyrobów dla budownictwa z tworzyw sztucznych",
							"C2229 - Produkcja pozostałych wyrobów z tworzyw sztucznych",
							"C2311 - Produkcja szkła płaskiego",
							"C2312 - Kształtowanie i obróbka szkła płaskiego",
							"C2313 - Produkcja szkła gospodarczego",
							"C2314 - Produkcja włókien szklanych",
							"C2319 - Produkcja i obróbka pozostałego szkła, włączając szkło techniczne",
							"C2320 - Produkcja wyrobów ogniotrwałych",
							"C2331 - Produkcja ceramicznych kafli i płytek",
							"C2332 - Produkcja cegieł, dachówek i materiałów budowlanych, z wypalanej gliny",
							"C2341 - Produkcja ceramicznych wyrobów stołowych i ozdobnych",
							"C2342 - Produkcja ceramicznych wyrobów sanitarnych",
							"C2343 - Produkcja ceramicznych izolatorów i osłon izolacyjnych",
							"C2344 - Produkcja pozostałych technicznych wyrobów ceramicznych",
							"C2349 - Produkcja pozostałych wyrobów ceramicznych",
							"C2351 - Produkcja cementu",
							"C2352 - Produkcja wapna i gipsu",
							"C2361 - Produkcja wyrobów budowlanych z betonu",
							"C2362 - Produkcja wyrobów budowlanych z gipsu",
							"C2363 - Produkcja masy betonowej prefabrykowanej",
							"C2364 - Produkcja zaprawy murarskiej",
							"C2365 - Produkcja cementu wzmocnionego włóknem",
							"C2369 - Produkcja pozostałych wyrobów z betonu, gipsu i cementu",
							"C2370 - Cięcie, formowanie i wykańczanie kamienia",
							"C2391 - Produkcja wyrobów ściernych",
							"C2399 - Produkcja pozostałych wyrobów z mineralnych surowców niemetalicznych, gdzie indziej niesklasyfikowana",
							"C2410 - Produkcja surówki, żelazostopów, żeliwa i stali oraz wyrobów hutniczych",
							"C2420 - Produkcja rur, przewodów, kształtowników zamkniętych i łączników, ze stali",
							"C2431 - Produkcja prętów ciągnionych na zimno",
							"C2432 - Produkcja wyrobów płaskich walcowanych na zimno",
							"C2433 - Produkcja wyrobów formowanych na zimno",
							"C2434 - Produkcja drutu",
							"C2441 - Produkcja metali szlachetnych",
							"C2442 - Produkcja aluminium",
							"C2443 - Produkcja ołowiu, cynku i cyny",
							"C2444 - Produkcja miedzi",
							"C2445 - Produkcja pozostałych metali nieżelaznych",
							"C2446 - Wytwarzanie paliw jądrowych",
							"C2451 - Odlewnictwo żeliwa",
							"C2452 - Odlewnictwo staliwa",
							"C2453 - Odlewnictwo metali lekkich",
							"C2454 - Odlewnictwo metali",
							"C2511 - Produkcja konstrukcji metalowych i ich części",
							"C2512 - Produkcja metalowych elementów stolarki budowlanej",
							"C2521 - Produkcja grzejników i kotłów centralnego ogrzewania",
							"C2529 - Produkcja pozostałych zbiorników, cystern i pojemników metalowych",
							"C2530 - Produkcja wytwornic pary, z wyłączeniem kotłów do centralnego ogrzewania gorącą wodą",
							"C2540 - Produkcja broni i amunicji",
							"C2550 - Kucie, prasowanie, wytłaczanie i walcowanie metali; metalurgia proszków",
							"C2561 - Obróbka metali i nakładanie powłok na metale",
							"C2562 - Obróbka mechaniczna elementów metalowych",
							"C2571 - Produkcja wyrobów nożowniczych i sztućców",
							"C2572 - Produkcja zamków i zawiasów",
							"C2573 - Produkcja narzędzi",
							"C2591 - Produkcja pojemników metalowych",
							"C2592 - Produkcja opakowań z metali",
							"C2593 - Produkcja wyrobów z drutu, łańcuchów i sprężyn",
							"C2594 - Produkcja złączy i śrub",
							"C2599 - Produkcja pozostałych gotowych wyrobów metalowych, gdzie indziej niesklasyfikowana",
							"C2611 - Produkcja elementów elektronicznych",
							"C2612 - Produkcja elektronicznych obwodów drukowanych",
							"C2620 - Produkcja komputerów i urządzeń peryferyjnych",
							"C2630 - Produkcja sprzętu (tele)komunikacyjnego",
							"C2640 - Produkcja elektronicznego sprzętu powszechnego użytku",
							"C2651 - Produkcja instrumentów i przyrządów pomiarowych, kontrolnych i nawigacyjnych",
							"C2652 - Produkcja zegarków i zegarów",
							"C2660 - Produkcja urządzeń napromieniowujących, sprzętu elektromedycznego i elektroterapeutycznego",
							"C2670 - Produkcja instrumentów optycznych i sprzętu fotograficznego",
							"C2680 - Produkcja magnetycznych i optycznych niezapisanych nośników informacji",
							"C2711 - Produkcja elektrycznych silników, prądnic i transformatorów",
							"C2712 - Produkcja aparatury rozdzielczej i sterowniczej energii elektrycznej",
							"C2720 - Produkcja baterii i akumulatorów",
							"C2731 - Produkcja kabli światłowodowych",
							"C2732 - Produkcja pozostałych elektronicznych i elektrycznych przewodów i kabli",
							"C2733 - Produkcja sprzętu instalacyjnego",
							"C2740 - Produkcja elektrycznego sprzętu oświetleniowego",
							"C2751 - Produkcja elektrycznego sprzętu gospodarstwa domowego",
							"C2752 - Produkcja nieelektrycznego sprzętu gospodarstwa domowego",
							"C2790 - Produkcja pozostałego sprzętu elektrycznego",
							"C2811 - Produkcja silników i turbin, z wyłączeniem silników lotniczych, samochodowych i motocyklowych",
							"C2812 - Produkcja sprzętu i wyposażenia do napędu hydraulicznego i pneumatycznego",
							"C2813 - Produkcja pozostałych pomp i sprężarek",
							"C2814 - Produkcja pozostałych kurków i zaworów",
							"C2815 - Produkcja łożysk, kół zębatych, przekładni zębatych i elementów napędowych",
							"C2821 - Produkcja pieców, palenisk i palników piecowych",
							"C2822 - Produkcja urządzeń dźwigowych i chwytaków",
							"C2823 - Produkcja maszyn i sprzętu biurowego, z wyłączeniem komputerów i urządzeń peryferyjnych",
							"C2824 - Produkcja narzędzi ręcznych mechanicznych",
							"C2825 - Produkcja przemysłowych urządzeń chłodniczych i wentylacyjnych",
							"C2829 - Produkcja pozostałych maszyn ogólnego przeznaczenia, gdzie indziej niesklasyfikowana",
							"C2830 - Produkcja maszyn dla rolnictwa i leśnictwa",
							"C2841 - Produkcja maszyn do obróbki metalu",
							"C2849 - Produkcja pozostałych narzędzi mechanicznych",
							"C2891 - Produkcja maszyn dla metalurgii",
							"C2892 - Produkcja maszyn dla górnictwa i do wydobywania oraz budownictwa",
							"C2893 - Produkcja maszyn stosowanych w przetwórstwie żywności, tytoniu i produkcji napojów",
							"C2894 - Produkcja maszyn dla przemysłu tekstylnego, odzieżowego i skórzanego",
							"C2895 - Produkcja maszyn dla przemysłu papierniczego",
							"C2896 - Produkcja maszyn do obróbki gumy lub tworzyw sztucznych oraz wytwarzania wyrobów z tych materiałów",
							"C2899 - Produkcja pozostałych maszyn specjalnego przeznaczenia, gdzie indziej niesklasyfikowana",
							"C2910 - Produkcja pojazdów",
							"C2920 - Produkcja nadwozi do pojazdów silnikowych; produkcja przyczep i naczep",
							"C2931 - Produkcja wyposażenia elektrycznego i elektronicznego do pojazdów silnikowych",
							"C2932 - Produkcja pozostałych części i akcesoriów do pojazdów silnikowych, z wyłączeniem motocykli",
							"C3011 - Produkcja statków i konstrukcji pływających",
							"C3012 - Produkcja łodzi wycieczkowych i sportowych",
							"C3020 - Produkcja lokomotyw kolejowych oraz taboru szynowego",
							"C3030 - Produkcja statków powietrznych, statków kosmicznych i podobnych maszyn",
							"C3040 - Produkcja wojskowych pojazdów bojowych",
							"C3091 - Produkcja motocykli",
							"C3092 - Produkcja rowerów i wózków inwalidzkich",
							"C3099 - Produkcja pozostałego sprzętu transportowego, gdzie indziej niesklasyfikowana",
							"C3101 - Produkcja mebli biurowych i sklepowych",
							"C3102 - Produkcja mebli kuchennych",
							"C3103 - Produkcja materaców",
							"C3109 - Produkcja pozostałych mebli",
							"C3211 - Produkcja monet",
							"C3212 - Produkcja wyrobów jubilerskich i podobnych",
							"C3213 - Produkcja sztucznej biżuterii i wyrobów podobnych",
							"C3220 - Produkcja instrumentów muzycznych",
							"C3230 - Produkcja sprzętu sportowego",
							"C3240 - Produkcja gier i zabawek",
							"C3250 - Produkcja urządzeń, instrumentów oraz wyrobów medycznych, włączając dentystyczne",
							"C3291 - Produkcja mioteł, szczotek i pędzli",
							"C3299 - Produkcja pozostałych wyrobów, gdzie indziej niesklasyfikowana",
							"C3311 - Naprawa i konserwacja metalowych wyrobów gotowych",
							"C3312 - Naprawa i konserwacja maszyn",
							"C3313 - Naprawa i konserwacja urządzeń elektronicznych i optycznych",
							"C3314 - Naprawa i konserwacja urządzeń elektrycznych",
							"C3315 - Naprawa i konserwacja statków i łodzi",
							"C3316 - Naprawa i konserwacja statków powietrznych i statków kosmicznych",
							"C3317 - Naprawa i konserwacja pozostałego sprzętu transportowego",
							"C3319 - Naprawa i konserwacja pozostałego sprzętu i wyposażenia",
							"C3320 - Instalowanie maszyn przemysłowych, sprzętu i wyposażenia",
							"D3511 - Wytwarzanie energii elektrycznej",
							"D3512 - Przesyłanie energii elektrycznej",
							"D3513 - Dystrybucja energii elektrycznej",
							"D3514 - Handel energią elektryczną",
							"D3521 - Wytwarzanie paliw gazowych",
							"D3522 - Dystrybucja paliw gazowych w systemie sieciowym",
							"D3523 - Handel paliwami gazowymi w systemie sieciowym",
							"D3530 - Wytwarzanie i zaopatrywanie w parę wodną, gorącą wodę i powietrze do układów klimatyzacyjnych",
							"E3600 - POBÓR, UZDATNIANIE I DOSTARCZANIE WODY",
							"E3700 - ODPROWADZANIE I OCZYSZCZANIE ŚCIEKÓW",
							"E3811 - Zbieranie odpadów innych niż niebezpieczne",
							"E3812 - Zbieranie odpadów niebezpiecznych",
							"E3821 - Obróbka i usuwanie odpadów innych niż niebezpieczne",
							"E3822 - Przetwarzanie i unieszkodliwianie odpadów niebezpiecznych",
							"E3831 - Demontaż wyrobów zużytych",
							"E3832 - Odzysk surowców z materiałów segregowanych",
							"E3900 - DZIAŁALNOŚĆ ZWIĄZANA Z REKULTYWACJĄ I POZOSTAŁA DZIAŁALNOŚĆ USŁUGOWA ZWIĄZANA Z GOSPODARKĄ ODPADAMI",
							"F4110 - Realizacja projektów budowlanych związanych ze wznoszeniem budynków",
							"F4120 - Roboty budowlane związane ze wznoszeniem budynków mieszkalnych i niemieszkalnych",
							"F4211 - Roboty związane z budową dróg i autostrad",
							"F4212 - Roboty związane z budową dróg szynowych i kolei podziemnej",
							"F4213 - Roboty związane z budową mostów i tuneli",
							"F4221 - Roboty związane z budową rurociągów przesyłowych i sieci rozdzielczych",
							"F4222 - Roboty związane z budową linii telekomunikacyjnych i elektroenergetycznych",
							"F4291 - Roboty związane z budową obiektów inżynierii wodnej",
							"F4299 - Roboty związane z budową pozostałych obiektów inżynierii lądowej i wodnej, gdzie indziej niesklasyfikowane",
							"F4311 - Rozbiórka i burzenie obiektów budowlanych",
							"F4312 - Przygotowanie terenu pod budowę",
							"F4313 - Wykonywanie wykopów i wierceń geologiczno-inżynierskich",
							"F4321 - Wykonywanie instalacji elektrycznych",
							"F4322 - Wykonywanie instalacji wodno-kanalizacyjnych, cieplnych, gazowych i klimatyzacyjnych",
							"F4329 - Wykonywanie pozostałych instalacji budowlanych",
							"F4331 - Tynkowanie",
							"F4332 - Zakładanie stolarki budowlanej",
							"F4333 - Posadzkarstwo; tapetowanie i oblicowywanie ścian",
							"F4334 - Malowanie i szklenie",
							"F4339 - Wykonywanie pozostałych robót budowlanych wykończeniowych",
							"F4391 - Wykonywanie konstrukcji i pokryć dachowych",
							"F4399 - Pozostałe specjalistyczne roboty budowlane, gdzie indziej niesklasyfikowane",
							"G4511 - Sprzedaż hurtowa i detaliczna samochodów osobowych i furgonetek",
							"G4519 - Sprzedaż hurtowa i detaliczna pozostałych pojazdów samochodowych, z wyłączeniem motocykli",
							"G4520 - Konserwacja i naprawa pojazdów samochodowych, z wyłączeniem motocykli",
							"G4531 - Sprzedaż hurtowa części i akcesoriów do pojazdów samochodowych, z wyłączeniem motocykli",
							"G4532 - Sprzedaż detaliczna części i akcesoriów do pojazdów samochodowych, z wyłączeniem motocykli",
							"G4540 - Sprzedaż hurtowa i detaliczna motocykli, ich naprawa i konserwacja oraz sprzedaż hurtowa i detaliczna części i akcesoriów do nich",
							"G4611 - Działalność agentów zajmujących się sprzedażą płodów rolnych, żywych zwierząt, surowców dla przemysłu tekstylnego i półproduktów",
							"G4612 - Działalność agentów zajmujących się sprzedażą paliw, rud, metali i chemikaliów przemysłowych",
							"G4613 - Działalność agentów zajmujących się sprzedażą drewna i materiałów budowlanych",
							"G4614 - Działalność agentów zajmujących się sprzedażą maszyn, urządzeń przemysłowych, statków i samolotów",
							"G4615 - Działalność agentów zajmujących się sprzedażą mebli, artykułów gospodarstwa domowego i drobnych wyrobów metalowych",
							"G4616 - Działalność agentów zajmujących się sprzedażą wyrobów tekstylnych, odzieży, wyrobów futrzarskich, obuwia i artykułów skórzanych",
							"G4617 - Działalność agentów zajmujących się sprzedażą żywności, napojów i wyrobów tytoniowych",
							"G4618 - Działalność agentów specjalizujących się w sprzedaży pozostałych określonych towarów",
							"G4619 - Działalność agentów zajmujących się sprzedażą towarów różnego rodzaju",
							"G4621 - Sprzedaż hurtowa zboża, nieprzetworzonego tytoniu, nasion i pasz dla zwierząt",
							"G4622 - Sprzedaż hurtowa kwiatów i roślin",
							"G4623 - Sprzedaż hurtowa żywych zwierząt",
							"G4624 - Sprzedaż hurtowa skór",
							"G4631 - Sprzedaż hurtowa owoców i warzyw",
							"G4632 - Sprzedaż hurtowa mięsa i wyrobów z mięsa",
							"G4633 - Sprzedaż hurtowa mleka, wyrobów mleczarskich, jaj, olejów i tłuszczów jadalnych",
							"G4634 - Sprzedaż hurtowa napojów alkoholowych i bezalkoholowych",
							"G4635 - Sprzedaż hurtowa wyrobów tytoniowych",
							"G4636 - Sprzedaż hurtowa cukru, czekolady, wyrobów cukierniczych i piekarskich",
							"G4637 - Sprzedaż hurtowa herbaty, kawy, kakao i przypraw",
							"G4638 - Sprzedaż hurtowa pozostałej żywności, włączając ryby, skorupiaki i mięczaki",
							"G4639 - Sprzedaż hurtowa niewyspecjalizowana żywności, napojów i wyrobów tytoniowych",
							"G4641 - Sprzedaż hurtowa wyrobów tekstylnych",
							"G4642 - Sprzedaż hurtowa odzieży i obuwia",
							"G4643 - Sprzedaż hurtowa elektrycznych artykułów użytku domowego",
							"G4644 - Sprzedaż hurtowa wyrobów porcelanowych, ceramicznych i szklanych oraz środków czyszczących",
							"G4645 - Sprzedaż hurtowa perfum i kosmetyków",
							"G4646 - Sprzedaż hurtowa wyrobów farmaceutycznych i medycznych",
							"G4647 - Sprzedaż hurtowa mebli, dywanów i sprzętu oświetleniowego",
							"G4648 - Sprzedaż hurtowa zegarków, zegarów i biżuterii",
							"G4649 - Sprzedaż hurtowa pozostałych artykułów użytku domowego",
							"G4651 - Sprzedaż hurtowa komputerów, urządzeń peryferyjnych i oprogramowania",
							"G4652 - Sprzedaż hurtowa sprzętu elektronicznego i telekomunikacyjnego oraz części do niego",
							"G4661 - Sprzedaż hurtowa maszyn i urządzeń rolniczych oraz dodatkowego wyposażenia",
							"G4662 - Sprzedaż hurtowa obrabiarek",
							"G4663 - Sprzedaż hurtowa maszyn wykorzystywanych w górnictwie, budownictwie oraz inżynierii lądowej i wodnej",
							"G4664 - Sprzedaż hurtowa maszyn dla przemysłu tekstylnego oraz maszyn do szycia i maszyn dziewiarskich",
							"G4665 - Sprzedaż hurtowa mebli biurowych",
							"G4666 - Sprzedaż hurtowa pozostałych maszyn i urządzeń biurowych",
							"G4669 - Sprzedaż hurtowa pozostałych maszyn i urządzeń",
							"G4671 - Sprzedaż hurtowa paliw i produktów pochodnych",
							"G4672 - Sprzedaż hurtowa metali i rud metali",
							"G4673 - Sprzedaż hurtowa drewna, materiałów budowlanych i wyposażenia sanitarnego",
							"G4674 - Sprzedaż hurtowa wyrobów metalowych oraz sprzętu i dodatkowego wyposażenia hydraulicznego i grzejnego",
							"G4675 - Sprzedaż hurtowa wyrobów chemicznych",
							"G4676 - Sprzedaż hurtowa pozostałych półproduktów",
							"G4677 - Sprzedaż hurtowa odpadów i złomu",
							"G4690 - Sprzedaż hurtowa niewyspecjalizowana",
							"G4711 - Sprzedaż detaliczna prowadzona w niewyspecjalizowanych sklepach z przewagą żywności, napojów i wyrobów tytoniowych",
							"G4719 - Pozostała sprzedaż detaliczna prowadzona w niewyspecjalizowanych sklepach",
							"G4721 - Sprzedaż detaliczna owoców i warzyw prowadzona w wyspecjalizowanych sklepach",
							"G4722 - Sprzedaż detaliczna mięsa i wyrobów z mięsa prowadzona w wyspecjalizowanych sklepach",
							"G4723 - Sprzedaż detaliczna ryb, skorupiaków i mięczaków prowadzona w wyspecjalizowanych sklepach",
							"G4724 - Sprzedaż detaliczna pieczywa, ciast, wyrobów ciastkarskich i cukierniczych prowadzona w wyspecjalizowanych sklepach",
							"G4725 - Sprzedaż detaliczna napojów alkoholowych i bezalkoholowych prowadzona w wyspecjalizowanych sklepach",
							"G4726 - Sprzedaż detaliczna wyrobów tytoniowych prowadzona w wyspecjalizowanych sklepach",
							"G4729 - Sprzedaż detaliczna pozostałej żywności prowadzona w wyspecjalizowanych sklepach",
							"G4730 - Sprzedaż detaliczna paliw do pojazdów silnikowych na stacjach paliw",
							"G4741 - Sprzedaż detaliczna komputerów, urządzeń peryferyjnych i oprogramowania prowadzona w wyspecjalizowanych sklepach",
							"G4742 - Sprzedaż detaliczna sprzętu telekomunikacyjnego prowadzona w wyspecjalizowanych sklepach",
							"G4743 - Sprzedaż detaliczna sprzętu audiowizualnego prowadzona w wyspecjalizowanych sklepach",
							"G4751 - Sprzedaż detaliczna wyrobów tekstylnych prowadzona w wyspecjalizowanych sklepach",
							"G4752 - Sprzedaż detaliczna drobnych wyrobów metalowych, farb i szkła prowadzona w wyspecjalizowanych sklepach",
							"G4753 - Sprzedaż detaliczna dywanów, chodników i innych pokryć podłogowych oraz pokryć ściennych prowadzona w wyspecjalizowanych sklepach",
							"G4754 - Sprzedaż detaliczna elektrycznego sprzętu gospodarstwa domowego prowadzona w wyspecjalizowanych sklepach",
							"G4759 - Sprzedaż detaliczna mebli, sprzętu oświetleniowego i pozostałych artykułów użytku domowego prowadzona w wyspecjalizowanych sklepach",
							"G4761 - Sprzedaż detaliczna książek prowadzona w wyspecjalizowanych sklepach",
							"G4762 - Sprzedaż detaliczna gazet i artykułów piśmiennych prowadzona w wyspecjalizowanych sklepach",
							"G4763 - Sprzedaż detaliczna nagrań dźwiękowych i audiowizualnych prowadzona w wyspecjalizowanych sklepach",
							"G4764 - Sprzedaż detaliczna sprzętu sportowego prowadzona w wyspecjalizowanych sklepach",
							"G4765 - Sprzedaż detaliczna gier i zabawek prowadzona w wyspecjalizowanych sklepach",
							"G4771 - Sprzedaż detaliczna odzieży prowadzona w wyspecjalizowanych sklepach",
							"G4772 - Sprzedaż detaliczna obuwia i wyrobów skórzanych prowadzona w wyspecjalizowanych sklepach",
							"G4773 - Sprzedaż detaliczna wyrobów farmaceutycznych prowadzona w wyspecjalizowanych sklepach",
							"G4774 - Sprzedaż detaliczna wyrobów medycznych, włączając ortopedyczne, prowadzona w wyspecjalizowanych sklepach",
							"G4775 - Sprzedaż detaliczna kosmetyków i artykułów toaletowych prowadzona w wyspecjalizowanych sklepach",
							"G4776 - Sprzedaż detaliczna kwiatów, roślin, nasion, nawozów, żywych zwierząt domowych, karmy dla zwierząt domowych prowadzona w wyspecjalizowanych sklepach",
							"G4777 - Sprzedaż detaliczna zegarków, zegarów i biżuterii prowadzona w wyspecjalizowanych sklepach",
							"G4778 - Sprzedaż detaliczna pozostałych nowych wyrobów prowadzona w wyspecjalizowanych sklepach",
							"G4779 - Sprzedaż detaliczna artykułów używanych prowadzona w wyspecjalizowanych sklepach",
							"G4781 - Sprzedaż detaliczna żywności, napojów i wyrobów tytoniowych prowadzona na straganach i targowiskach",
							"G4782 - Sprzedaż detaliczna wyrobów tekstylnych, odzieży i obuwia prowadzona na straganach i targowiskach",
							"G4789 - Sprzedaż detaliczna pozostałych wyrobów prowadzona na straganach i targowiskach",
							"G4791 - Sprzedaż detaliczna prowadzona przez domy sprzedaży wysyłkowej lub Internet",
							"G4799 - Pozostała sprzedaż detaliczna prowadzona poza siecią sklepową, straganami i targowiskami",
							"H4910 - Transport kolejowy pasażerski międzymiastowy",
							"H4920 - Transport kolejowy towarów",
							"H4931 - Transport lądowy pasażerski, miejski i podmiejski",
							"H4932 - Działalność taksówek osobowych",
							"H4939 - Pozostały transport lądowy pasażerski, gdzie indziej niesklasyfikowany",
							"H4941 - Transport drogowy towarów",
							"H4942 - Działalność usługowa związana z przeprowadzkami",
							"H4950 - Transport rurociągowy",
							"H5010 - Transport morski i przybrzeżny pasażerski",
							"H5020 - Transport morski i przybrzeżny towarów",
							"H5030 - Transport wodny śródlądowy pasażerski",
							"H5040 - Transport wodny śródlądowy towarów",
							"H5110 - Transport lotniczy pasażerski",
							"H5121 - Transport lotniczy towarów",
							"H5122 - Transport kosmiczny",
							"H5210 - Magazynowanie i przechowywanie",
							"H5221 - Działalność usługowa wspomagająca transport lądowy",
							"H5222 - Działalność usługowa wspomagająca transport",
							"H5223 - Działalność usługowa wspomagająca transport lotniczy",
							"H5224 - Przeładunek towarów",
							"H5229 - Działalność agencji transportowych",
							"H5310 - Działalność pocztowa objęta obowiązkiem świadczenia usług powszechnych (operatora publicznego)",
							"H5320 - Pozostała działalność pocztowa i kurierska",
							"I5510 - Hotele i podobne obiekty zakwaterowania",
							"I5520 - Obiekty noclegowe turystyczne i miejsca krótkotrwałego zakwaterowania",
							"I5530 - Pola kempingowe (włączając pola dla pojazdów kempingowych) i pola namiotowe",
							"I5590 - Pozostałe zakwaterowanie",
							"I5610 - Placówki gastronomiczne",
							"I5621 - Przygotowywanie i dostarczanie żywności dla odbiorców zewnętrznych (katering)",
							"I5629 - Pozostała usługowa działalność gastronomiczna",
							"I5630 - Przygotowywanie i podawanie napojów",
							"J5811 - Wydawanie książek",
							"J5812 - Wydawanie wykazów oraz list (np. adresowych, telefonicznych)",
							"J5813 - Wydawanie gazet",
							"J5814 - Wydawanie czasopism i pozostałych periodyków",
							"J5819 - Pozostała działalność wydawnicza",
							"J5821 - Działalność wydawnicza w zakresie gier komputerowych",
							"J5829 - Działalność wydawnicza w zakresie pozostałego oprogramowania",
							"J5911 - Działalność związana z produkcją filmów, nagrań wideo i programów telewizyjnych",
							"J5912 - Działalność postprodukcyjna związana z filmami, nagraniami wideo i programami telewizyjnymi",
							"J5913 - Działalność związana z dystrybucją filmów, nagrań wideo i programów telewizyjnych",
							"J5914 - Działalność związana z projekcją filmów",
							"J5920 - Działalność w zakresie nagrań dźwiękowych i muzycznych",
							"J6010 - Nadawanie programów radiofonicznych",
							"J6020 - Nadawanie programów telewizyjnych ogólnodostępnych i abonamentowych",
							"J6110 - Działalność w zakresie telekomunikacji przewodowej",
							"J6120 - Działalność w zakresie telekomunikacji bezprzewodowej, z wyłączeniem telekomunikacji satelitarnej",
							"J6130 - Działalność w zakresie telekomunikacji satelitarnej",
							"J6190 - Działalność w zakresie pozostałej telekomunikacji",
							"J6201 - Działalność związana z oprogramowaniem",
							"J6202 - Działalność związana z doradztwem w zakresie informatyki",
							"J6203 - Działalność związana z zarządzaniem urządzeniami informatycznymi",
							"J6209 - Pozostała działalność usługowa w zakresie technologii informatycznych i komputerowych",
							"J6311 - Przetwarzanie danych; zarządzanie stronami internetowymi (hosting) i podobna działalność",
							"J6312 - Działalność portali internetowych",
							"J6391 - Działalność agencji informacyjnych",
							"J6399 - Pozostała działalność usługowa w zakresie informacji, gdzie indziej niesklasyfikowana",
							"K6411 - Działalność banku centralnego",
							"K6419 - Pozostałe pośrednictwo pieniężne",
							"K6420 - Działalność holdingów finansowych",
							"K6430 - Działalność trustów, funduszów i podobnych instytucji finansowych",
							"K6491 - Leasing finansowy",
							"K6492 - Pozostałe formy udzielania kredytów",
							"K6499 - Pozostała finansowa działalność usługowa, gdzie indziej niesklasyfikowana, z wyłączeniem ubezpieczeń i funduszów emerytalnych",
							"K6511 - Ubezpieczenia na życie",
							"K6512 - Pozostałe ubezpieczenia osobowe oraz ubezpieczenia majątkowe",
							"K6520 - Reasekuracja",
							"K6530 - Fundusze emerytalne",
							"K6611 - Zarządzanie rynkami finansowymi",
							"K6612 - Działalność maklerska związana z rynkiem papierów wartościowych i towarów giełdowych",
							"K6619 - Pozostała działalność wspomagająca usługi finansowe, z wyłączeniem ubezpieczeń i funduszów emerytalnych",
							"K6621 - Działalność związana z oceną ryzyka i szacowaniem poniesionych strat",
							"K6622 - Działalność agentów i brokerów ubezpieczeniowych",
							"K6629 - Pozostała działalność wspomagająca ubezpieczenia i fundusze emerytalne",
							"K6630 - Działalność związana z zarządzaniem funduszami",
							"L6810 - Kupno i sprzedaż nieruchomości na własny rachunek",
							"L6820 - Wynajem i zarządzanie nieruchomościami własnymi lub dzierżawionymi",
							"L6831 - Pośrednictwo w obrocie nieruchomościami",
							"L6832 - Zarządzanie nieruchomościami wykonywane na zlecenie",
							"M6910 - Działalność prawnicza",
							"M6920 - Działalność rachunkowo-księgowa; doradztwo podatkowe",
							"M7010 - Działalność firm centralnych (head offices) i holdingów, z wyłączeniem holdingów finansowych",
							"M7021 - Stosunki międzyludzkie (public relations) i komunikacja",
							"M7022 - Pozostałe doradztwo w zakresie prowadzenia działalności gospodarczej i zarządzania",
							"M7111 - Działalność w zakresie architektury",
							"M7112 - Działalność w zakresie inżynierii i związane z nią doradztwo techniczne",
							"M7120 - Badania i analizy techniczne",
							"M7211 - Badania naukowe i prace rozwojowe w dziedzinie biotechnologii",
							"M7219 - Badania naukowe i prace rozwojowe w dziedzinie pozostałych nauk przyrodniczych i technicznych",
							"M7220 - Badania naukowe i prace rozwojowe w dziedzinie nauk społecznych i humanistycznych",
							"M7311 - Działalność agencji reklamowych",
							"M7312 - Pośrednictwo w sprzedaży miejsca na cele reklamowe",
							"M7320 - Badanie rynku i opinii publicznej",
							"M7410 - Działalność w zakresie specjalistycznego projektowania",
							"M7420 - Działalność fotograficzna",
							"M7430 - Działalność związana z tłumaczeniami",
							"M7490 - Pozostała działalność profesjonalna, naukowa i techniczna, gdzie indziej niesklasyfikowana",
							"M7500 - DZIAŁALNOŚĆ WETERYNARYJNA",
							"N7711 - Wynajem i dzierżawa samochodów osobowych i furgonetek",
							"N7712 - Wynajem i dzierżawa pozostałych pojazdów samochodowych, z wyłączeniem motocykli",
							"N7721 - Wypożyczanie i dzierżawa sprzętu rekreacyjnego i sportowego",
							"N7722 - Wypożyczanie kaset wideo, płyt CD, DVD itp.",
							"N7729 - Wypożyczanie i dzierżawa pozostałych artykułów użytku osobistego i domowego",
							"N7731 - Wynajem i dzierżawa maszyn i urządzeń rolniczych",
							"N7732 - Wynajem i dzierżawa maszyn i urządzeń budowlanych",
							"N7733 - Wynajem i dzierżawa maszyn i urządzeń biurowych, włączając komputery",
							"N7734 - Wynajem i dzierżawa środków transportu wodnego",
							"N7735 - Wynajem i dzierżawa środków transportu lotniczego",
							"N7739 - Wynajem i dzierżawa pozostałych maszyn, urządzeń oraz dóbr materialnych, gdzie indziej niesklasyfikowane",
							"N7740 - Dzierżawa własności intelektualnej i podobnych produktów, z wyłączeniem prac chronionych prawem autorskim",
							"N7810 - Działalność związana z wyszukiwaniem miejsc pracy i pozyskiwaniem pracowników",
							"N7820 - Działalność agencji pracy tymczasowej",
							"N7830 - Pozostała działalność związana z udostępnianiem pracowników",
							"N7911 - Działalność agentów i pośredników turystycznych",
							"N7912 - Działalność organizatorów turystyki",
							"N7990 - Działalność turystyczna",
							"N8010 - Działalność ochroniarska, z wyłączeniem obsługi systemów bezpieczeństwa",
							"N8020 - Działalność ochroniarska w zakresie obsługi systemów bezpieczeństwa",
							"N8030 - Działalność detektywistyczna",
							"N8110 - Działalność pomocnicza związana z utrzymaniem porządku w budynkach",
							"N8121 - Niespecjalistyczne sprzątanie budynków i obiektów przemysłowych",
							"N8122 - Specjalistyczne sprzątanie budynków i obiektów przemysłowych",
							"N8129 - Pozostałe sprzątanie",
							"N8130 - Działalność usługowa związana z zagospodarowaniem terenów zieleni",
							"N8211 - Działalność usługowa związana z administracyjną obsługą biura",
							"N8219 - Wykonywanie fotokopii, przygotowywanie dokumentów i pozostała specjalistyczna działalność wspomagająca prowadzenie biura",
							"N8220 - Działalność centrów telefonicznych (call center)",
							"N8230 - Działalność związana z organizacją targów, wystaw i kongresów",
							"N8291 - Działalność świadczona przez agencje inkasa i biura kredytowe",
							"N8292 - Działalność związana z pakowaniem",
							"N8299 - Pozostała działalność wspomagająca prowadzenie działalności gospodarczej, gdzie indziej niesklasyfikowana",
							"O8411 - Kierowanie podstawowymi rodzajami działalności publicznej",
							"O8412 - Kierowanie w zakresie działalności związanej z ochroną zdrowia, edukacją, kulturą oraz pozostałymi usługami społecznymi, z wyłączeniem zabezpieczeń społecznych",
							"O8413 - Kierowanie w zakresie efektywności gospodarowania",
							"O8421 - Sprawy zagraniczne",
							"O8422 - Obrona narodowa",
							"O8423 - Wymiar sprawiedliwości",
							"O8424 - Bezpieczeństwo państwa, porządek i bezpieczeństwo publiczne",
							"O8425 - Ochrona przeciwpożarowa",
							"O8430 - Obowiązkowe zabezpieczenia społeczne",
							"P8510 - Wychowanie przedszkolne",
							"P8520 - Szkoły podstawowe",
							"P8531 - Gimnazja i licea",
							"P8532 - Technika i szkoły zawodowe",
							"P8541 - Szkoły policealne",
							"P8542 - Szkoły wyższe",
							"P8551 - Pozaszkolne formy edukacji sportowej oraz zajęć sportowych i rekreacyjnych",
							"P8552 - Pozaszkolne formy edukacji artystycznej",
							"P8553 - Pozaszkolne formy edukacji z zakresu nauki jazdy i pilotażu",
							"P8559 - Pozaszkolne formy edukacji, w tym nauka języków obcych",
							"P8560 - Działalność wspomagająca edukację",
							"Q8610 - Działalność szpitali",
							"Q8621 - Praktyka lekarska ogólna",
							"Q8622 - Praktyka lekarska specjalistyczna",
							"Q8623 - Praktyka lekarska dentystyczna",
							"Q8690 - Działalność w zakresie opieki zdrowotnej",
							"Q8710 - Pomoc społeczna z zakwaterowaniem zapewniająca opiekę pielęgniarską",
							"Q8720 - Pomoc społeczna z zakwaterowaniem dla osób z zaburzeniami psychicznymi",
							"Q8730 - Pomoc społeczna z zakwaterowaniem dla osób w podeszłym wieku i osób niepełnosprawnych",
							"Q8790 - Pozostała pomoc społeczna z zakwaterowaniem",
							"Q8810 - Pomoc społeczna bez zakwaterowania dla osób w podeszłym wieku i osób niepełnosprawnych",
							"Q8891 - Opieka dzienna nad dziećmi",
							"Q8899 - Pozostała pomoc społeczna bez zakwaterowania, gdzie indziej niesklasyfikowana",
							"R9001 - Działalność związana z wystawianiem przedstawień artystycznych",
							"R9002 - Działalność wspomagająca wystawianie przedstawień artystycznych",
							"R9003 - Artystyczna i literacka działalność twórcza",
							"R9004 - Działalność obiektów kulturalnych",
							"R9101 - Biblioteki i archiwa",
							"R9102 - Działalność muzeów",
							"R9103 - Działalność historycznych miejsc i budynków oraz podobnych atrakcji turystycznych",
							"R9104 - Działalność ogrodów botanicznych i zoologicznych oraz obszarów i obiektów ochrony przyrody",
							"R9200 - DZIAŁALNOŚĆ ZWIĄZANA Z GRAMI LOSOWYMI I ZAKŁADAMI WZAJEMNYMI",
							"R9311 - Działalność obiektów sportowych",
							"R9312 - Działalność klubów sportowych",
							"R9313 - Działalność obiektów służących poprawie kondycji fizycznej",
							"R9319 - Pozostała działalność związana ze sportem",
							"R9321 - Działalność wesołych miasteczek i parków rozrywki",
							"R9329 - Pozostała działalność rozrywkowa i rekreacyjna",
							"S9411 - Działalność organizacji komercyjnych i pracodawców",
							"S9412 - Działalność organizacji profesjonalnych",
							"S9420 - Działalność związków zawodowych",
							"S9491 - Działalność organizacji religijnych",
							"S9492 - Działalność organizacji politycznych",
							"S9499 - Działalność pozostałych organizacji członkowskich, gdzie indziej niesklasyfikowana",
							"S9511 - Naprawa i konserwacja komputerów i urządzeń peryferyjnych",
							"S9512 - Naprawa i konserwacja sprzętu (tele)komunikacyjnego",
							"S9521 - Naprawa i konserwacja elektronicznego sprzętu powszechnego użytku",
							"S9522 - Naprawa i konserwacja urządzeń gospodarstwa domowego oraz sprzętu użytku domowego i ogrodniczego",
							"S9523 - Naprawa obuwia i wyrobów skórzanych",
							"S9524 - Naprawa i konserwacja mebli i wyposażenia domowego",
							"S9525 - Naprawa zegarów, zegarków oraz biżuterii",
							"S9529 - Naprawa pozostałych artykułów użytku osobistego i domowego",
							"S9601 - Pranie i czyszczenie wyrobów włókienniczych i futrzarskich",
							"S9602 - Fryzjerstwo i pozostałe zabiegi kosmetyczne",
							"S9603 - Pogrzeby i działalność pokrewna",
							"S9604 - Działalność usługowa związana z poprawą kondycji fizycznej",
							"S9609 - Pozostała działalność usługowa, gdzie indziej niesklasyfikowana",
							"T9700 - GOSPODARSTWA DOMOWE ZATRUDNIAJĄCE PRACOWNIKÓW",
							"T9810 - Gospodarstwa domowe produkujące wyroby na własne potrzeby",
							"T9820 - Gospodarstwa domowe świadczące usługi na własne potrzeby",
							"U9900 - ORGANIZACJE I ZESPOŁY EKSTERYTORIALNE"]`;